// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetSitApp.Models;

#nullable disable

namespace PetSitApp.Migrations.PetSitApp
{
    [DbContext(typeof(PetSitAppContext))]
    [Migration("20260312041515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetSitApp.Models.DaysUnavailable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("SitterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SitterId");

                    b.ToTable("DaysUnavailable", (string)null);
                });

            modelBuilder.Entity("PetSitApp.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasDefaultValueSql("(0x)");

                    b.Property<string>("State")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Zip")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_Owners_UserId")
                        .IsUnique();

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("PetSitApp.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_Permissions_UserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("PetSitApp.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("AdoptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Care")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Chipped")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnergyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedingSchedule")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Friendly")
                        .HasColumnType("bit");

                    b.Property<string>("LeftAlone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalInformation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<bool>("PottyTrained")
                        .HasColumnType("bit");

                    b.Property<bool>("Spayed")
                        .HasColumnType("bit");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VetInformation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OwnerId" }, "IX_Pets_OwnerId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetSitApp.Models.PetPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Picture")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("PetPictures");
                });

            modelBuilder.Entity("PetSitApp.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SitterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetId");

                    b.HasIndex("SitterId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("PetSitApp.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PetType")
                        .HasColumnType("int");

                    b.Property<int>("SitterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SitterId" }, "IX_Services")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("PetSitApp.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceOffered")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("PetSitApp.Models.Sitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_Sitters")
                        .IsUnique();

                    b.ToTable("Sitters");
                });

            modelBuilder.Entity("PetSitApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetSitApp.Models.WeekAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Friday")
                        .HasColumnType("bit");

                    b.Property<bool>("Monday")
                        .HasColumnType("bit");

                    b.Property<bool>("Saturday")
                        .HasColumnType("bit");

                    b.Property<int>("SitterId")
                        .HasColumnType("int");

                    b.Property<bool>("Sunday")
                        .HasColumnType("bit");

                    b.Property<bool>("Thursday")
                        .HasColumnType("bit");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SitterId" }, "IX_WeekAvailabilities")
                        .IsUnique();

                    b.ToTable("WeekAvailabilities");
                });

            modelBuilder.Entity("PetSitApp.Models.DaysUnavailable", b =>
                {
                    b.HasOne("PetSitApp.Models.Sitter", "Sitter")
                        .WithMany("DaysUnavailables")
                        .HasForeignKey("SitterId")
                        .IsRequired()
                        .HasConstraintName("FK_DaysUnavailable_Sitters");

                    b.Navigation("Sitter");
                });

            modelBuilder.Entity("PetSitApp.Models.Owner", b =>
                {
                    b.HasOne("PetSitApp.Models.User", "User")
                        .WithOne("Owner")
                        .HasForeignKey("PetSitApp.Models.Owner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetSitApp.Models.Permission", b =>
                {
                    b.HasOne("PetSitApp.Models.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetSitApp.Models.Pet", b =>
                {
                    b.HasOne("PetSitApp.Models.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetSitApp.Models.PetPicture", b =>
                {
                    b.HasOne("PetSitApp.Models.Pet", "Pet")
                        .WithMany("PetPictures")
                        .HasForeignKey("PetId")
                        .IsRequired()
                        .HasConstraintName("FK_PetPictures_Pets");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetSitApp.Models.Reservation", b =>
                {
                    b.HasOne("PetSitApp.Models.Owner", "Owner")
                        .WithMany("Reservations")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Owners");

                    b.HasOne("PetSitApp.Models.Pet", "Pet")
                        .WithMany("Reservations")
                        .HasForeignKey("PetId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Pets");

                    b.HasOne("PetSitApp.Models.Sitter", "Sitter")
                        .WithMany("Reservations")
                        .HasForeignKey("SitterId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Sitters");

                    b.Navigation("Owner");

                    b.Navigation("Pet");

                    b.Navigation("Sitter");
                });

            modelBuilder.Entity("PetSitApp.Models.Service", b =>
                {
                    b.HasOne("PetSitApp.Models.Sitter", "Sitter")
                        .WithOne("Service")
                        .HasForeignKey("PetSitApp.Models.Service", "SitterId")
                        .IsRequired();

                    b.Navigation("Sitter");
                });

            modelBuilder.Entity("PetSitApp.Models.ServiceType", b =>
                {
                    b.HasOne("PetSitApp.Models.Service", "Service")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_ServiceTypes_Services");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PetSitApp.Models.Sitter", b =>
                {
                    b.HasOne("PetSitApp.Models.User", "User")
                        .WithOne("Sitter")
                        .HasForeignKey("PetSitApp.Models.Sitter", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetSitApp.Models.WeekAvailability", b =>
                {
                    b.HasOne("PetSitApp.Models.Sitter", "Sitter")
                        .WithOne("WeekAvailability")
                        .HasForeignKey("PetSitApp.Models.WeekAvailability", "SitterId")
                        .IsRequired()
                        .HasConstraintName("FK_WeekAvailabilities_Sitters");

                    b.Navigation("Sitter");
                });

            modelBuilder.Entity("PetSitApp.Models.Owner", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("PetSitApp.Models.Pet", b =>
                {
                    b.Navigation("PetPictures");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("PetSitApp.Models.Service", b =>
                {
                    b.Navigation("ServiceTypes");
                });

            modelBuilder.Entity("PetSitApp.Models.Sitter", b =>
                {
                    b.Navigation("DaysUnavailables");

                    b.Navigation("Reservations");

                    b.Navigation("Service");

                    b.Navigation("WeekAvailability");
                });

            modelBuilder.Entity("PetSitApp.Models.User", b =>
                {
                    b.Navigation("Owner");

                    b.Navigation("Permissions");

                    b.Navigation("Sitter");
                });
#pragma warning restore 612, 618
        }
    }
}
